name: trhinehart
favicon: null
layout_spectrum: 0.29735
typography_spectrum: 0.5292776662390679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
